os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
  include:
    - name: "checks"
      script:
      - docker run  -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap:cpp scripts/checks.sh
    - name: "tests"
      script:
      - docker run -e TRAVIS_REPO_SLUG=`$TRAVIS_REPO_SLUG` -e TRAVIS_PULL_REQUEST=$(TRAVIS_PULL_REQUEST) -e TRAVIS_BRANCH=$(TRAVIS_BRANCH) -e TRAVIS_COMMIT=$(TRAVIS_COMMIT) -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap:cpp scripts/tests.sh

notifications:
    email: false
